/**
 * Natural TTS service for F.R.I.D.A.Y.
 * Plays British Neural voice generated by backend Edge-TTS with Web Speech API fallback.
 * Supports instant interruption via stopSpeaking() which immediately resolves any pending speak() promise.
 */

let currentAudio = null;
let currentResolve = null; // Holds the pending speak() promise resolver for instant abort

/**
 * Instantly stop any currently playing audio and resolve the pending speak() promise,
 * so the await speak(...) in useSpeech.js returns immediately.
 */
export function stopSpeaking() {
  // Resolve pending promise immediately so await speak() returns and loop continues
  if (currentResolve) {
    const resolve = currentResolve;
    currentResolve = null;
    resolve();
    console.log('[TTS] Speech interrupted — stopped mid-sentence.');
  }

  // Hard-stop browser audio element
  if (currentAudio) {
    try {
      currentAudio.pause();
      currentAudio.currentTime = 0;
    } catch (_) {}
    currentAudio = null;
  }

  // Cancel Web Speech API fallback
  if ('speechSynthesis' in window) {
    window.speechSynthesis.cancel();
  }
}

export async function speak(text) {
  if (!text || typeof text !== 'string') return;

  // Only stop a PREVIOUS audio if something is actively playing
  // (do NOT call stopSpeaking() unconditionally — that would abort our own promise)
  if (currentAudio) {
    try { currentAudio.pause(); currentAudio.currentTime = 0; } catch (_) {}
    currentAudio = null;
  }
  if ('speechSynthesis' in window) {
    window.speechSynthesis.cancel();
  }

  try {
    const response = await fetch('http://localhost:8000/api/tts', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text }),
    });

    if (response.ok) {
      const data = await response.json();
      if (data.audio_url) {
        return new Promise((resolve) => {
          // Store resolver so stopSpeaking() can resolve this promise instantly from outside
          currentResolve = resolve;

          const audio = new Audio(data.audio_url);
          currentAudio = audio;

          audio.onended = () => {
            currentAudio = null;
            if (currentResolve === resolve) {
              currentResolve = null;
              resolve();
            }
          };

          audio.onerror = () => {
            currentAudio = null;
            if (currentResolve === resolve) {
              currentResolve = null;
            }
            fallbackWebSpeech(text, resolve);
          };

          audio.play().catch(() => {
            currentAudio = null;
            if (currentResolve === resolve) {
              currentResolve = null;
            }
            fallbackWebSpeech(text, resolve);
          });
        });
      }
    }
  } catch (err) {
    console.warn('[TTS] Backend TTS error, using browser fallback:', err);
  }

  return new Promise((resolve) => {
    currentResolve = resolve;
    fallbackWebSpeech(text, () => {
      if (currentResolve === resolve) {
        currentResolve = null;
      }
      resolve();
    });
  });
}

function fallbackWebSpeech(text, onEnd) {
  if (!('speechSynthesis' in window)) {
    if (onEnd) onEnd();
    return;
  }
  window.speechSynthesis.cancel();
  const utterance = new SpeechSynthesisUtterance(text);
  utterance.pitch = 1.0;
  utterance.rate = 1.05;

  const voices = window.speechSynthesis.getVoices();
  const ukVoice = voices.find(v => v.lang.includes('en-GB') || v.name.includes('UK') || v.name.includes('Victoria') || v.name.includes('Karen'));
  if (ukVoice) utterance.voice = ukVoice;

  utterance.onend = () => { if (onEnd) onEnd(); };
  utterance.onerror = () => { if (onEnd) onEnd(); };
  window.speechSynthesis.speak(utterance);
}
