/**
 * Natural TTS service for F.R.I.D.A.Y.
 * Plays British Neural voice generated by backend Edge-TTS with Web Speech API fallback.
 */
let currentAudio = null;

export async function speak(text) {
  if (!text || typeof text !== 'string') return;

  // Stop any currently playing speech
  if (currentAudio) {
    currentAudio.pause();
    currentAudio = null;
  }

  try {
    const response = await fetch('http://localhost:8000/api/tts', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text }),
    });

    if (response.ok) {
      const data = await response.json();
      if (data.audio_url) {
        return new Promise((resolve) => {
          const audio = new Audio(data.audio_url);
          currentAudio = audio;
          audio.onended = () => {
            currentAudio = null;
            resolve();
          };
          audio.onerror = () => {
            fallbackWebSpeech(text, resolve);
          };
          audio.play().catch(() => fallbackWebSpeech(text, resolve));
        });
      }
    }
  } catch (err) {
    console.warn('[TTS] Backend TTS error, using browser fallback:', err);
  }

  return new Promise((resolve) => fallbackWebSpeech(text, resolve));
}

function fallbackWebSpeech(text, onEnd) {
  if (!('speechSynthesis' in window)) {
    if (onEnd) onEnd();
    return;
  }
  window.speechSynthesis.cancel();
  const utterance = new SpeechSynthesisUtterance(text);
  utterance.pitch = 1.0;
  utterance.rate = 1.05;

  const voices = window.speechSynthesis.getVoices();
  const ukVoice = voices.find(v => v.lang.includes('en-GB') || v.name.includes('UK') || v.name.includes('Victoria') || v.name.includes('Karen'));
  if (ukVoice) utterance.voice = ukVoice;

  utterance.onend = () => { if (onEnd) onEnd(); };
  utterance.onerror = () => { if (onEnd) onEnd(); };
  window.speechSynthesis.speak(utterance);
}
